modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Hellish-Mods/Hellish-Powah/"
license="LGPLv3"

[[mods]]
modId="powah"
version="${file.jarVersion}"
displayName="Hellish Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii, Rainbuu"
description='''
A fork of the mod Powah to add more customizability for Modern Modpacks.
'''

[[dependencies.powah]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"
